<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-09T00:36:41Z" name="Default suite" finished-at="2023-02-09T00:37:09Z" duration-ms="28341">
    <groups>
    </groups>
    <test started-at="2023-02-09T00:36:41Z" name="Default test" finished-at="2023-02-09T00:37:09Z" duration-ms="28341">
      <class name="test.YourStoreTest">
        <test-method signature="registerAccount()[pri:0, instance:test.YourStoreTest@68f4865]" started-at="2023-02-09T00:36:41Z" name="registerAccount" finished-at="2023-02-09T00:36:48Z" duration-ms="7098" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerAccount -->
        <test-method signature="searchByLowest()[pri:0, instance:test.YourStoreTest@68f4865]" started-at="2023-02-09T00:36:48Z" name="searchByLowest" finished-at="2023-02-09T00:36:50Z" depends-on-methods="test.YourStoreTest.registerAccount" duration-ms="2343" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchByLowest -->
        <test-method signature="verifyItemsCart()[pri:0, instance:test.YourStoreTest@68f4865]" started-at="2023-02-09T00:36:50Z" name="verifyItemsCart" finished-at="2023-02-09T00:36:53Z" depends-on-methods="test.YourStoreTest.registerAccount" duration-ms="2534" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at test.YourStoreTest.verifyItemsCart(YourStoreTest.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyItemsCart -->
        <test-method signature="estimateShippingAndCheckoutAlert()[pri:0, instance:test.YourStoreTest@68f4865]" started-at="2023-02-09T00:36:53Z" name="estimateShippingAndCheckoutAlert" finished-at="2023-02-09T00:36:53Z" depends-on-methods="test.YourStoreTest.verifyItemsCart" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method YourStoreTest.estimateShippingAndCheckoutAlert()[pri:0, instance:test.YourStoreTest@68f4865] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method YourStoreTest.estimateShippingAndCheckoutAlert()[pri:0, instance:test.YourStoreTest@68f4865] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimateShippingAndCheckoutAlert -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:test.YourStoreTest@68f4865]" started-at="2023-02-09T00:36:53Z" name="cleanUp" finished-at="2023-02-09T00:37:09Z" duration-ms="16345" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- test.YourStoreTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
